# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

zeroplanedisCpp2 <- function(h, pai) {
    .Call(`_micropoint_zeroplanedisCpp2`, h, pai)
}

roughlengthCpp2 <- function(h, pai, d) {
    .Call(`_micropoint_roughlengthCpp2`, h, pai, d)
}

dpsimCpp2 <- function(ze) {
    .Call(`_micropoint_dpsimCpp2`, ze)
}

satvapCpp2 <- function(tc) {
    .Call(`_micropoint_satvapCpp2`, tc)
}

geometricCpp <- function(n, totalDepth) {
    .Call(`_micropoint_geometricCpp`, n, totalDepth)
}

Tabove <- function(za, zref, th, tref, hgt, pai, LL = 1e99) {
    .Call(`_micropoint_Tabove`, za, zref, th, tref, hgt, pai, LL)
}

RHabove <- function(za, zref, rh, th, tref, tz, relhum, hgt, pai, LL = 1e99) {
    .Call(`_micropoint_RHabove`, za, zref, rh, th, tref, tz, relhum, hgt, pai, LL)
}

Uabove <- function(za, zref, uh, uref, hgt, pai, LL) {
    .Call(`_micropoint_Uabove`, za, zref, uh, uref, hgt, pai, LL)
}

PenmanMonteith_animal <- function(Rabs, Ta, Ts, Te, Tf, pk, rh, rHa, height, rc, confrac, M, em = 0.97, k = 0.5, surfrh = 1.0) {
    .Call(`_micropoint_PenmanMonteith_animal`, Rabs, Ta, Ts, Te, Tf, pk, rh, rHa, height, rc, confrac, M, em, k, surfrh)
}

Ectotherm <- function(obstime, climdata, animal, lat, lon, leaft, maxIter = 100L, tolerance = 1e-2) {
    .Call(`_micropoint_Ectotherm`, obstime, climdata, animal, lat, lon, leaft, maxIter, tolerance)
}

EctothermM <- function(obstime, climdata, animal, lat, lon, leaft, maxIter = 100L, tolerance = 1e-2) {
    .Call(`_micropoint_EctothermM`, obstime, climdata, animal, lat, lon, leaft, maxIter, tolerance)
}

reverseCumsum <- function(paii) {
    .Call(`_micropoint_reverseCumsum`, paii)
}

profilebareR <- function(hourtoplot, obstime, climdata, soilc, z, zref, lat, lon, SoilTempIni, SoilThetaIni, zm = 0.004, maxNrIterations = 100L, tolerance = 1e-3) {
    .Call(`_micropoint_profilebareR`, hourtoplot, obstime, climdata, soilc, z, zref, lat, lon, SoilTempIni, SoilThetaIni, zm, maxNrIterations, tolerance)
}

profileR <- function(hourtoplot, obstime, climdata, soilc, vegp, paii20, paii, Lfrac20, Lfrac, zref, Ca, lat, lon, SoilTempIni, SoilThetaIni, maxNrIterations = 100L, tolerance = 1e-3, a0 = 0.25, a1 = 1.25, C3 = TRUE) {
    .Call(`_micropoint_profileR`, hourtoplot, obstime, climdata, soilc, vegp, paii20, paii, Lfrac20, Lfrac, zref, Ca, lat, lon, SoilTempIni, SoilThetaIni, maxNrIterations, tolerance, a0, a1, C3)
}

RunBareR <- function(reqhgt, obstime, climdata, soilc, zref, lat, lon, SoilTempIni, SoilThetaIni, zm = 0.004, maxNrIterations = 100L, tolerance = 1e-3) {
    .Call(`_micropoint_RunBareR`, reqhgt, obstime, climdata, soilc, zref, lat, lon, SoilTempIni, SoilThetaIni, zm, maxNrIterations, tolerance)
}

RunModelR <- function(reqhgt, obstime, climdata, soilc, vegp, paii, Lfrac, zref, Ca, lat, lon, SoilTempIni, SoilThetaIni, maxNrIterations = 100L, tolerance = 1e-3, a0 = 0.25, a1 = 1.25, C3 = TRUE) {
    .Call(`_micropoint_RunModelR`, reqhgt, obstime, climdata, soilc, vegp, paii, Lfrac, zref, Ca, lat, lon, SoilTempIni, SoilThetaIni, maxNrIterations, tolerance, a0, a1, C3)
}

WeatherhgtCpp2 <- function(obstime, climdata, soilc, vegp, paii, Lfrac, zin, zout, lat, lon, SoilTempIni, SoilThetaIni, CO2ppm = 430.0) {
    .Call(`_micropoint_WeatherhgtCpp2`, obstime, climdata, soilc, vegp, paii, Lfrac, zin, zout, lat, lon, SoilTempIni, SoilThetaIni, CO2ppm)
}

RunBelowFullBare <- function(obstime, climdata, soilc, z, zref, zm, lat, lon, SoilTempIni, SoilThetaIni, maxNrIterations = 100L, tolerance = 1e-2) {
    .Call(`_micropoint_RunBelowFullBare`, obstime, climdata, soilc, z, zref, zm, lat, lon, SoilTempIni, SoilThetaIni, maxNrIterations, tolerance)
}

RunBelowFull <- function(obstime, climdata, soilc, vegp, paii, Lfrac, zref, Ca, lat, lon, SoilTempIni, SoilThetaIni, maxNrIterations = 100L, tolerance = 1e-2, a0 = 0.25, a1 = 1.25, C3 = TRUE) {
    .Call(`_micropoint_RunBelowFull`, obstime, climdata, soilc, vegp, paii, Lfrac, zref, Ca, lat, lon, SoilTempIni, SoilThetaIni, maxNrIterations, tolerance, a0, a1, C3)
}

clearskyradCpp2 <- function(obstime, climdata, lat, lon) {
    .Call(`_micropoint_clearskyradCpp2`, obstime, climdata, lat, lon)
}

difpropCpp <- function(obstime, swrad, lat, lon) {
    .Call(`_micropoint_difpropCpp`, obstime, swrad, lat, lon)
}

solaltCpp <- function(obstime, lat, lon) {
    .Call(`_micropoint_solaltCpp`, obstime, lat, lon)
}

expand_outputCpp <- function(mat, nout) {
    .Call(`_micropoint_expand_outputCpp`, mat, nout)
}

BigLeafCpp2 <- function(obstime, climdata, soilc, vegp, Lfrac, zref, Ca, lat, lon, boundaryT, maxiter = 100L, C3 = TRUE) {
    .Call(`_micropoint_BigLeafCpp2`, obstime, climdata, soilc, vegp, Lfrac, zref, Ca, lat, lon, boundaryT, maxiter, C3)
}

BigLeafBareCpp <- function(obstime, climdata, soilc, zref, zmr, lat, lon, boundaryT, maxiter = 100L, C3 = TRUE) {
    .Call(`_micropoint_BigLeafBareCpp`, obstime, climdata, soilc, zref, zmr, lat, lon, boundaryT, maxiter, C3)
}

