# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

solpositionCpp <- function(lat, lon, year, month, day, lt) {
    .Call(`_micropoint_solpositionCpp`, lat, lon, year, month, day, lt)
}

solarindexCpp <- function(slope, aspect, zen, azi, shadowmask = FALSE) {
    .Call(`_micropoint_solarindexCpp`, slope, aspect, zen, azi, shadowmask)
}

clearskyradCpp <- function(year, month, day, lt, lat, lon, tc, rh, pk) {
    .Call(`_micropoint_clearskyradCpp`, year, month, day, lt, lat, lon, tc, rh, pk)
}

zeroplanedisCpp <- function(h, pai) {
    .Call(`_micropoint_zeroplanedisCpp`, h, pai)
}

roughlengthCpp <- function(h, pai, d, psi_h) {
    .Call(`_micropoint_roughlengthCpp`, h, pai, d, psi_h)
}

dpsimCpp <- function(ze) {
    .Call(`_micropoint_dpsimCpp`, ze)
}

dpsihCpp <- function(ze) {
    .Call(`_micropoint_dpsihCpp`, ze)
}

dphihCpp <- function(ze) {
    .Call(`_micropoint_dphihCpp`, ze)
}

satvapCpp <- function(tc) {
    .Call(`_micropoint_satvapCpp`, tc)
}

dewpointCpp <- function(tc, ea) {
    .Call(`_micropoint_dewpointCpp`, tc, ea)
}

PenmanMonteithCpp <- function(Rabs, gHa, gV, tc, te, pk, ea, em, G, erh) {
    .Call(`_micropoint_PenmanMonteithCpp`, Rabs, gHa, gV, tc, te, pk, ea, em, G, erh)
}

hourtodayCpp <- function(hourly, stat) {
    .Call(`_micropoint_hourtodayCpp`, hourly, stat)
}

maCpp <- function(x, n) {
    .Call(`_micropoint_maCpp`, x, n)
}

mayCpp <- function(x) {
    .Call(`_micropoint_mayCpp`, x)
}

BigLeafCpp <- function(obstime, climdata, vegp, groundp, soilm, lat, lon, dTmx = 25.0, zref = 2.0, maxiter = 100L, bwgt = 0.5, tol = 0.5, gmn = 0.1, yearG = TRUE) {
    .Call(`_micropoint_BigLeafCpp`, obstime, climdata, vegp, groundp, soilm, lat, lon, dTmx, zref, maxiter, bwgt, tol, gmn, yearG)
}

weatherhgtCpp <- function(obstime, climdata, zin, uzin, zout, lat, lon, yearG = TRUE) {
    .Call(`_micropoint_weatherhgtCpp`, obstime, climdata, zin, uzin, zout, lat, lon, yearG)
}

meandtrCpp <- function(temp) {
    .Call(`_micropoint_meandtrCpp`, temp)
}

adjustdtrCpp <- function(temp, dtrc) {
    .Call(`_micropoint_adjustdtrCpp`, temp, dtrc)
}

dtr_correctCpp <- function(obstime, climdata, zin, uzin, zout, lat, lon, yearG = TRUE) {
    .Call(`_micropoint_dtr_correctCpp`, obstime, climdata, zin, uzin, zout, lat, lon, yearG)
}

soilmCpp <- function(climdata, rmu, mult, pwr, Smax, Smin, Ksat, a) {
    .Call(`_micropoint_soilmCpp`, climdata, rmu, mult, pwr, Smax, Smin, Ksat, a)
}

CanopyWindCpp <- function(hgt, paii) {
    .Call(`_micropoint_CanopyWindCpp`, hgt, paii)
}

SmallLeafOne <- function(reqhgt, zref, lat, lon, obsvars, climvars, bigleafvars, maxiters, wc, vegp, paii, groundp, tleaf, tair, ea, surfwet, z, a0 = 0.25, a1 = 1.25, bwgt = 0.5) {
    .Call(`_micropoint_SmallLeafOne`, reqhgt, zref, lat, lon, obsvars, climvars, bigleafvars, maxiters, wc, vegp, paii, groundp, tleaf, tair, ea, surfwet, z, a0, a1, bwgt)
}

BelowCanopy <- function(reqhgt, zref, lat, lon, obstime, climdata, bigleafvars, iters, vegp, paii, groundp, a0 = 0.25, a1 = 1.25, bwgt = 0.5) {
    .Call(`_micropoint_BelowCanopy`, reqhgt, zref, lat, lon, obstime, climdata, bigleafvars, iters, vegp, paii, groundp, a0, a1, bwgt)
}

AboveCanopy <- function(reqhgt, zref, lat, lon, obstime, climdata, bigleafvars, vegp) {
    .Call(`_micropoint_AboveCanopy`, reqhgt, zref, lat, lon, obstime, climdata, bigleafvars, vegp)
}

manCpp <- function(x, n) {
    .Call(`_micropoint_manCpp`, x, n)
}

Belowground <- function(reqhgt, bigleafvars, groundp) {
    .Call(`_micropoint_Belowground`, reqhgt, bigleafvars, groundp)
}

Atground <- function(lat, lon, obstime, climdata, bigleafvars, vegp, groundp) {
    .Call(`_micropoint_Atground`, lat, lon, obstime, climdata, bigleafvars, vegp, groundp)
}

runmodel <- function(reqhgt, zref, lat, lon, obstime, climdata, bigleafvars, iters, vegp, paii, groundp, a0 = 0.25, a1 = 1.25, bwgt = 0.5) {
    .Call(`_micropoint_runmodel`, reqhgt, zref, lat, lon, obstime, climdata, bigleafvars, iters, vegp, paii, groundp, a0, a1, bwgt)
}

satvapCpp2 <- function(tc) {
    .Call(`_micropoint_satvapCpp2`, tc)
}

geometricCpp <- function(n, totalDepth) {
    .Call(`_micropoint_geometricCpp`, n, totalDepth)
}

Tabove <- function(za, zref, th, tref, hgt, pai) {
    .Call(`_micropoint_Tabove`, za, zref, th, tref, hgt, pai)
}

RHabove <- function(za, zref, rh, th, tref, tz, relhum, hgt, pai) {
    .Call(`_micropoint_RHabove`, za, zref, rh, th, tref, tz, relhum, hgt, pai)
}

Uabove <- function(za, zref, uh, uref, hgt, pai, LL) {
    .Call(`_micropoint_Uabove`, za, zref, uh, uref, hgt, pai, LL)
}

reverseCumsum <- function(paii) {
    .Call(`_micropoint_reverseCumsum`, paii)
}

profilebareR <- function(hourtoplot, obstime, climdata, soilc, z, zref, lat, lon, SoilTempIni, SoilThetaIni, zm = 0.004, maxNrIterations = 100L, tolerance = 1e-3) {
    .Call(`_micropoint_profilebareR`, hourtoplot, obstime, climdata, soilc, z, zref, lat, lon, SoilTempIni, SoilThetaIni, zm, maxNrIterations, tolerance)
}

profileR <- function(hourtoplot, obstime, climdata, soilc, vegp, paii20, paii, Lfrac20, Lfrac, zref, Ca, lat, lon, SoilTempIni, SoilThetaIni, maxNrIterations = 100L, tolerance = 1e-3, a0 = 0.25, a1 = 1.25, C3 = TRUE) {
    .Call(`_micropoint_profileR`, hourtoplot, obstime, climdata, soilc, vegp, paii20, paii, Lfrac20, Lfrac, zref, Ca, lat, lon, SoilTempIni, SoilThetaIni, maxNrIterations, tolerance, a0, a1, C3)
}

RunBareR <- function(reqhgt, obstime, climdata, soilc, zref, lat, lon, SoilTempIni, SoilThetaIni, zm = 0.004, maxNrIterations = 100L, tolerance = 1e-3) {
    .Call(`_micropoint_RunBareR`, reqhgt, obstime, climdata, soilc, zref, lat, lon, SoilTempIni, SoilThetaIni, zm, maxNrIterations, tolerance)
}

RunModelR <- function(reqhgt, obstime, climdata, soilc, vegp, paii, Lfrac, zref, Ca, lat, lon, SoilTempIni, SoilThetaIni, maxNrIterations = 100L, tolerance = 1e-3, a0 = 0.25, a1 = 1.25, C3 = TRUE) {
    .Call(`_micropoint_RunModelR`, reqhgt, obstime, climdata, soilc, vegp, paii, Lfrac, zref, Ca, lat, lon, SoilTempIni, SoilThetaIni, maxNrIterations, tolerance, a0, a1, C3)
}

WeatherhgtCpp2 <- function(obstime, climdata, soilc, vegp, paii, Lfrac, zin, zout, lat, lon, SoilTempIni, SoilThetaIni, CO2ppm = 430.0) {
    .Call(`_micropoint_WeatherhgtCpp2`, obstime, climdata, soilc, vegp, paii, Lfrac, zin, zout, lat, lon, SoilTempIni, SoilThetaIni, CO2ppm)
}

RunBelowFullBare <- function(obstime, climdata, soilc, z, zref, zm, lat, lon, SoilTempIni, SoilThetaIni, maxNrIterations = 100L, tolerance = 1e-2) {
    .Call(`_micropoint_RunBelowFullBare`, obstime, climdata, soilc, z, zref, zm, lat, lon, SoilTempIni, SoilThetaIni, maxNrIterations, tolerance)
}

RunBelowFull <- function(obstime, climdata, soilc, vegp, paii, Lfrac, zref, Ca, lat, lon, SoilTempIni, SoilThetaIni, maxNrIterations = 100L, tolerance = 1e-2, a0 = 0.25, a1 = 1.25, C3 = TRUE) {
    .Call(`_micropoint_RunBelowFull`, obstime, climdata, soilc, vegp, paii, Lfrac, zref, Ca, lat, lon, SoilTempIni, SoilThetaIni, maxNrIterations, tolerance, a0, a1, C3)
}

clearskyradCpp2 <- function(obstime, climdata, lat, lon) {
    .Call(`_micropoint_clearskyradCpp2`, obstime, climdata, lat, lon)
}

difpropCpp <- function(obstime, swrad, lat, lon) {
    .Call(`_micropoint_difpropCpp`, obstime, swrad, lat, lon)
}

solaltCpp <- function(obstime, lat, lon) {
    .Call(`_micropoint_solaltCpp`, obstime, lat, lon)
}

expand_outputCpp <- function(mat, nout) {
    .Call(`_micropoint_expand_outputCpp`, mat, nout)
}

